<script setup>
import { onMounted,reactive,ref } from 'vue'
import { useRouter } from 'vue-router'
import http from '../api/http'
import { useAuthStore } from '../stores/auth'
import { dateText,statusText } from '../utils/format'
import { Location,Clock,Search,User } from '@element-plus/icons-vue'
const filterVisible=ref(false),records=ref([]),total=ref(0),loading=ref(false),router=useRouter(),auth=useAuthStore()
const query=reactive({page:1,size:10,keyword:'',category:'',status:'RECRUITING',location:'',minReward:null,maxReward:null,startTime:'',endTime:'',sort:'deadline'})
const categories=['校园活动','课程辅导','生活服务','物品代取','创意设计','其他']
const statuses=[['RECRUITING','招募中'],['WAIT_EXECUTE','待执行'],['IN_PROGRESS','进行中'],['WAIT_ACCEPTANCE','待验收'],['COMPLETED','已完成'],['CANCELLED','已取消'],['ABNORMAL','异常']]
async function load(){loading.value=true;try{const params={...query};Object.keys(params).forEach(k=>(params[k]===''||params[k]===null)&&delete params[k]);const data=await http.get('/api/public/tasks',{params});records.value=data.records;total.value=data.total}finally{loading.value=false}}
function search(){query.page=1;load()}function open(id){router.push(`/tasks/${id}`)}onMounted(load)
</script>
<template><div><div class="page-head"><div><h1>任务广场</h1><p>发现身边的小需求，用可靠行动赢得积分与信用</p></div><el-button type="primary" size="large" @click="router.push(auth.loggedIn?'/tasks/new':'/login')">发布微任务</el-button></div>
<div class="filter-bar surface"><el-input v-model="query.keyword" clearable placeholder="搜索任务、地点或关键词" @keyup.enter="search"><template #prefix><el-icon><Search/></el-icon></template></el-input><el-select class="desktop-filter" v-model="query.category" clearable placeholder="全部分类" @change="search"><el-option v-for="c in categories" :key="c" :label="c" :value="c"/></el-select><el-select class="desktop-filter" v-model="query.status" clearable placeholder="全部状态" @change="search"><el-option v-for="item in statuses" :key="item[0]" :label="item[1]" :value="item[0]"/></el-select><el-select class="desktop-filter" v-model="query.sort" @change="search"><el-option label="截止时间优先" value="deadline"/><el-option label="最新发布" value="newest"/><el-option label="积分从高到低" value="rewardDesc"/><el-option label="积分从低到高" value="rewardAsc"/></el-select><el-button class="desktop-filter" @click="search">筛选</el-button><el-button class="mobile-filter" @click="filterVisible=true">筛选</el-button></div>
<div v-loading="loading" class="grid"><article v-for="task in records" :key="task.id" class="task-card surface" @click="open(task.id)"><div class="card-top"><el-tag effect="plain" type="success">{{task.category}}</el-tag><span class="status-pill">{{statusText(task.status)}}</span></div><h3>{{task.title}}</h3><p class="task-summary">{{task.descriptionSummary||'暂无任务摘要'}}</p><div class="meta-row"><el-icon><Location/></el-icon>{{task.location||'地点待沟通'}}</div><div class="meta-row"><el-icon><Clock/></el-icon>任务 {{dateText(task.taskTime)}}</div><div class="meta-row"><el-icon><Clock/></el-icon>截止 {{dateText(task.applicationDeadline)}}</div><div class="meta-row"><el-icon><User/></el-icon>{{task.applicationCount||0}} 人申请</div><div class="card-bottom"><span class="muted">{{task.publisherNickname}} · 信用 {{task.publisherCredit}}</span><span class="points">{{task.rewardPoints}}<small style="font:12px sans-serif"> 积分</small></span></div></article></div>
<div v-if="!loading&&!records.length" class="surface empty">暂时没有符合条件的任务，换个条件试试</div><div class="pager"><el-pagination v-if="total>query.size" v-model:current-page="query.page" :page-size="query.size" :total="total" layout="prev,pager,next" @current-change="load"/></div>
<el-drawer v-model="filterVisible" title="筛选任务" direction="btt" size="520px"><el-form label-position="top"><el-form-item label="分类"><el-select v-model="query.category" clearable><el-option v-for="c in categories" :key="c" :label="c" :value="c"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option v-for="item in statuses" :key="item[0]" :label="item[1]" :value="item[0]"/></el-select></el-form-item><el-form-item label="地点"><el-input v-model="query.location" clearable/></el-form-item><el-form-item label="奖励积分"><div class="range"><el-input-number v-model="query.minReward" :min="1" placeholder="最低"/><span>至</span><el-input-number v-model="query.maxReward" :min="1" placeholder="最高"/></div></el-form-item><el-form-item label="任务时间"><div class="range"><el-date-picker v-model="query.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="开始"/><span>至</span><el-date-picker v-model="query.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="结束"/></div></el-form-item><el-form-item label="排序"><el-select v-model="query.sort"><el-option label="截止时间优先" value="deadline"/><el-option label="最新发布" value="newest"/><el-option label="积分从高到低" value="rewardDesc"/><el-option label="积分从低到高" value="rewardAsc"/></el-select></el-form-item><el-button type="primary" @click="search();filterVisible=false">应用筛选</el-button></el-form></el-drawer></div></template>
<style scoped>.mobile-filter{display:none}.task-summary{color:#5f6965;line-height:1.6;min-height:3.2em}.pager{display:flex;justify-content:center;margin-top:26px}.range{display:flex;align-items:center;gap:8px;flex-wrap:wrap}@media(max-width:640px){.desktop-filter{display:none}.mobile-filter{display:inline-flex}}</style>