<script setup>
import { computed,onMounted,reactive,ref,watch } from 'vue'
import http from '../api/http'
import { dateText } from '../utils/format'
import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(),data=ref({availablePoints:0,frozenPoints:0,creditScore:0,pointTransactions:{records:[]},creditRecords:{records:[]}}),reviews=ref({records:[],total:0}),tab=ref('points'),query=reactive({page:1,size:10})
const creditGrade=computed(()=>data.value.creditScore>=90?'极佳':data.value.creditScore>=80?'优秀':data.value.creditScore>=60?'良好':'一般')
const pageTotal=computed(()=>tab.value==='points'?(data.value.pointTransactions.total||0):tab.value==='credit'?(data.value.creditRecords.total||0):(reviews.value.total||0))
async function load(){const values=await Promise.all([http.get('/api/wallet',{params:query}),http.get(`/api/reviews/users/${auth.user.id}`,{params:query})]);data.value=values[0];reviews.value=values[1]}
watch(tab,()=>{query.page=1;load()})
onMounted(async()=>{await auth.refresh();await load()})
</script>
<template><div><div class="page-head"><div><h1>积分与信用</h1><p>每一笔变动都有迹可循，可靠履约让信用持续积累</p></div></div><div class="stat-grid" style="margin-bottom:20px"><div class="stat surface"><strong>{{data.availablePoints}}</strong><span>可用积分</span></div><div class="stat surface"><strong>{{data.frozenPoints}}</strong><span>冻结积分</span></div><div class="stat surface"><strong>{{data.creditScore}}</strong><span>信用分 · {{creditGrade}}</span></div></div><section class="surface panel"><el-tabs v-model="tab"><el-tab-pane label="积分流水" name="points"><div v-for="tx in data.pointTransactions.records" :key="tx.id" class="list-card record"><div><strong>{{tx.remark||tx.businessType}}</strong><div class="muted">{{dateText(tx.createdAt)}} · 余额 {{tx.beforeBalance}} → {{tx.afterBalance}}</div></div><strong :style="{color:tx.changeAmount>=0?'#2f7d68':'#bf4c4c'}">{{tx.changeAmount>0?'+':''}}{{tx.changeAmount}}</strong></div><div v-if="!data.pointTransactions.records?.length" class="empty">暂无积分流水</div></el-tab-pane><el-tab-pane label="信用记录" name="credit"><div v-for="r in data.creditRecords.records" :key="r.id" class="list-card record"><div><strong>{{r.reason}}</strong><div class="muted">{{dateText(r.createdAt)}} · {{r.beforeScore}} → {{r.afterScore}}</div></div><strong :style="{color:r.changeValue>=0?'#2f7d68':'#bf4c4c'}">{{r.changeValue>0?'+':''}}{{r.changeValue}}</strong></div><div v-if="!data.creditRecords.records?.length" class="empty">暂无信用变动</div></el-tab-pane><el-tab-pane label="收到的评价" name="reviews"><div v-for="r in reviews.records" :key="r.id" class="list-card"><div class="record"><el-rate :model-value="r.rating" disabled/><span class="muted">{{dateText(r.createdAt)}}</span></div><p>{{r.content||'未填写评价内容'}}</p></div><div v-if="!reviews.records.length" class="empty">暂无评价</div></el-tab-pane></el-tabs><div class="pager"><el-pagination v-if="pageTotal>query.size" v-model:current-page="query.page" :total="pageTotal" :page-size="query.size" layout="prev,pager,next" @current-change="load"/></div></section></div></template>
<style scoped>.record{background:#f5f7f3;display:flex;justify-content:space-between;gap:12px}.record .muted{margin-top:6px}.pager{display:flex;justify-content:center}</style>
