package com.campuslink.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.campuslink.common.BusinessException;
import com.campuslink.domain.*;
import com.campuslink.dto.Requests;
import com.campuslink.mapper.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;

@Service @RequiredArgsConstructor
public class GovernanceService {
    private final ReviewMapper reviewMapper;private final ReportMapper reportMapper;private final TaskOrderMapper orderMapper;private final SkillExchangeMapper exchangeMapper;private final UserMapper userMapper;private final TaskMapper taskMapper;private final SkillMapper skillMapper;private final AccountService accountService;private final PointCreditService pointCreditService;
    @Transactional public Review review(Long reviewerId,Requests.ReviewCreate dto){
        if(reviewerId.equals(dto.revieweeId()))throw new BusinessException("不能评价自己");boolean participant=false;
        if("TASK".equals(dto.businessType())){TaskOrder o=orderMapper.selectById(dto.businessId());participant=o!=null&&"COMPLETED".equals(o.getStatus())&&((reviewerId.equals(o.getPublisherId())&&dto.revieweeId().equals(o.getAccepterId()))||(reviewerId.equals(o.getAccepterId())&&dto.revieweeId().equals(o.getPublisherId())));}else if("SKILL_EXCHANGE".equals(dto.businessType())){SkillExchange e=exchangeMapper.selectById(dto.businessId());participant=e!=null&&"COMPLETED".equals(e.getStatus())&&((reviewerId.equals(e.getRequesterId())&&dto.revieweeId().equals(e.getProviderId()))||(reviewerId.equals(e.getProviderId())&&dto.revieweeId().equals(e.getRequesterId())));}if(!participant)throw new BusinessException("仅已完成业务的参与者可以评价");
        if(reviewMapper.selectCount(new LambdaQueryWrapper<Review>().eq(Review::getBusinessType,dto.businessType()).eq(Review::getBusinessId,dto.businessId()).eq(Review::getReviewerId,reviewerId))>0)throw new BusinessException("该业务已评价");Review r=new Review();r.setBusinessType(dto.businessType());r.setBusinessId(dto.businessId());r.setReviewerId(reviewerId);r.setRevieweeId(dto.revieweeId());r.setRating(dto.rating());r.setContent(dto.content());r.setCreatedAt(LocalDateTime.now());reviewMapper.insert(r);if(dto.rating()>=4)pointCreditService.changeCredit(accountService.requiredUser(dto.revieweeId()),2,"HIGH_RATING",dto.businessId(),"获得4~5星评价");else if(dto.rating()<=2)pointCreditService.changeCredit(accountService.requiredUser(dto.revieweeId()),-3,"LOW_RATING",dto.businessId(),"获得1~2星评价");return r;
    }
    public List<Review> reviews(Long userId){return reviewMapper.selectList(new LambdaQueryWrapper<Review>().eq(Review::getRevieweeId,userId).orderByDesc(Review::getCreatedAt));}
    public Report report(Long reporterId,Requests.ReportCreate dto){Report r=new Report();r.setReporterId(reporterId);r.setTargetType(dto.targetType());r.setTargetId(dto.targetId());r.setReasonType(dto.reasonType());r.setDescription(dto.description());r.setStatus("PENDING");r.setCreatedAt(LocalDateTime.now());reportMapper.insert(r);return r;}
    public List<Report> myReports(Long userId){return reportMapper.selectList(new LambdaQueryWrapper<Report>().eq(Report::getReporterId,userId).orderByDesc(Report::getCreatedAt));}
    public Map<String,Object> dashboard(){Map<String,Object>m=new LinkedHashMap<>();m.put("users",userMapper.selectCount(new LambdaQueryWrapper<User>().eq(User::getRole,"STUDENT")));m.put("recruitingTasks",taskMapper.selectCount(new LambdaQueryWrapper<CampusTask>().eq(CampusTask::getStatus,"RECRUITING")));m.put("activeTasks",taskMapper.selectCount(new LambdaQueryWrapper<CampusTask>().in(CampusTask::getStatus,List.of("WAIT_EXECUTE","IN_PROGRESS","WAIT_ACCEPTANCE"))));m.put("completedTasks",taskMapper.selectCount(new LambdaQueryWrapper<CampusTask>().eq(CampusTask::getStatus,"COMPLETED")));m.put("pendingReports",reportMapper.selectCount(new LambdaQueryWrapper<Report>().eq(Report::getStatus,"PENDING")));return m;}
    public Map<String,Object> users(int page,int size,String status){LambdaQueryWrapper<User> q=new LambdaQueryWrapper<User>().orderByDesc(User::getCreatedAt);if(status!=null&&!status.isBlank())q.eq(User::getStatus,status);Page<User> p=userMapper.selectPage(Page.of(Math.max(1,page),bounded(size)),q);return pageData(p,p.getRecords().stream().map(AuthService::userView).toList());}
    public Map<String,Object> tasks(int page,int size,String status){LambdaQueryWrapper<CampusTask> q=new LambdaQueryWrapper<CampusTask>().orderByDesc(CampusTask::getCreatedAt);if(status!=null&&!status.isBlank())q.eq(CampusTask::getStatus,status);Page<CampusTask> p=taskMapper.selectPage(Page.of(Math.max(1,page),bounded(size)),q);return pageData(p,p.getRecords());}
    public Map<String,Object> reports(int page,int size,String status){LambdaQueryWrapper<Report> q=new LambdaQueryWrapper<Report>().orderByAsc(Report::getStatus).orderByDesc(Report::getCreatedAt);if(status!=null&&!status.isBlank())q.eq(Report::getStatus,status);Page<Report> p=reportMapper.selectPage(Page.of(Math.max(1,page),bounded(size)),q);return pageData(p,p.getRecords());}
    @Transactional public Report handleReport(Long adminId,Long id,Requests.ReportHandle dto){Report r=reportMapper.selectById(id);if(r==null)throw new BusinessException("举报不存在");if(r.getPreviousStatus()!=null)throw new BusinessException("异常任务请使用异常裁决接口处理");if("RESOLVED".equals(r.getStatus()))throw new BusinessException("举报已处理");r.setStatus("RESOLVED");r.setHandlerId(adminId);r.setHandleResult(dto.result());r.setHandledAt(LocalDateTime.now());reportMapper.updateById(r);accountService.notify(r.getReporterId(),"SYSTEM_NOTICE","举报处理完成",dto.result(),r.getId());return r;}
    public Map<String,Object> setUserStatus(Long id,String status){if(!Set.of("NORMAL","BANNED").contains(status))throw new BusinessException("状态值无效");User u=accountService.requiredUser(id);if("ADMIN".equals(u.getRole()))throw new BusinessException("不能禁用管理员");u.setStatus(status);u.setUpdatedAt(LocalDateTime.now());userMapper.updateById(u);return AuthService.userView(u);}
    public Skill addSkill(String name,String category){if(name==null||name.isBlank()||category==null||category.isBlank())throw new BusinessException("技能名称和分类不能为空");Skill existing=skillMapper.selectOne(new LambdaQueryWrapper<Skill>().eq(Skill::getName,name));if(existing!=null){existing.setStatus("ENABLED");existing.setCategory(category);skillMapper.updateById(existing);return existing;}Skill s=new Skill();s.setName(name);s.setCategory(category);s.setStatus("ENABLED");s.setCreatedAt(LocalDateTime.now());skillMapper.insert(s);return s;}
    public Skill setSkillStatus(Long id,String status){if(!Set.of("ENABLED","DISABLED").contains(status))throw new BusinessException("状态值无效");Skill s=skillMapper.selectById(id);if(s==null)throw new BusinessException("技能不存在");s.setStatus(status);skillMapper.updateById(s);return s;}
    public List<Skill> allSkills(){return skillMapper.selectList(new LambdaQueryWrapper<Skill>().orderByAsc(Skill::getCategory,Skill::getName));}
    private int bounded(int size){return Math.min(100,Math.max(1,size));}private Map<String,Object> pageData(Page<?> page,Object records){Map<String,Object> m=new LinkedHashMap<>();m.put("records",records);m.put("total",page.getTotal());m.put("page",page.getCurrent());m.put("size",page.getSize());m.put("pages",page.getPages());return m;}
}
