package com.campuslink.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.campuslink.common.BusinessException;
import com.campuslink.domain.*;
import com.campuslink.dto.Requests;
import com.campuslink.mapper.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

@Service @RequiredArgsConstructor
public class SkillService {
    private final SkillMapper skillMapper;private final UserSkillMapper offerMapper;private final UserSkillNeedMapper needMapper;private final UserMapper userMapper;private final ReviewMapper reviewMapper;private final TaskOrderMapper orderMapper;private final SkillExchangeMapper exchangeMapper;private final AccountService accountService;
    public List<Skill> skills(){return skillMapper.selectList(new LambdaQueryWrapper<Skill>().eq(Skill::getStatus,"ENABLED").orderByAsc(Skill::getCategory,Skill::getName));}
    public Map<String,Object> profile(Long userId){Map<Long,Skill> skillMap=skillMapper.selectList(null).stream().collect(Collectors.toMap(Skill::getId,Function.identity()));Map<String,Object> m=new LinkedHashMap<>();m.put("offers",offerMapper.selectList(new LambdaQueryWrapper<UserSkill>().eq(UserSkill::getUserId,userId)).stream().map(o->withSkill(o,skillMap.get(o.getSkillId()))).toList());m.put("needs",needMapper.selectList(new LambdaQueryWrapper<UserSkillNeed>().eq(UserSkillNeed::getUserId,userId)).stream().map(n->withSkill(n,skillMap.get(n.getSkillId()))).toList());return m;}
    @Transactional public void saveOffer(Long userId,Requests.SkillOffer dto){requiredSkill(dto.skillId());UserSkill o=offerMapper.selectOne(new LambdaQueryWrapper<UserSkill>().eq(UserSkill::getUserId,userId).eq(UserSkill::getSkillId,dto.skillId()));if(o==null){o=new UserSkill();o.setUserId(userId);o.setSkillId(dto.skillId());o.setCreatedAt(LocalDateTime.now());}o.setProficiency(dto.proficiency());o.setDescription(dto.description());o.setAvailableMode(dto.availableMode());if(o.getId()==null)offerMapper.insert(o);else offerMapper.updateById(o);}
    @Transactional public void saveNeed(Long userId,Requests.SkillNeed dto){requiredSkill(dto.skillId());UserSkillNeed n=needMapper.selectOne(new LambdaQueryWrapper<UserSkillNeed>().eq(UserSkillNeed::getUserId,userId).eq(UserSkillNeed::getSkillId,dto.skillId()));if(n==null){n=new UserSkillNeed();n.setUserId(userId);n.setSkillId(dto.skillId());n.setCreatedAt(LocalDateTime.now());}n.setPriority(dto.priority()==null?1:dto.priority());n.setDescription(dto.description());n.setPreferredMode(dto.preferredMode());if(n.getId()==null)needMapper.insert(n);else needMapper.updateById(n);}
    public void deleteOffer(Long userId,Long id){UserSkill o=offerMapper.selectById(id);if(o==null||!userId.equals(o.getUserId()))throw new BusinessException("技能供给不存在");offerMapper.deleteById(id);} public void deleteNeed(Long userId,Long id){UserSkillNeed n=needMapper.selectById(id);if(n==null||!userId.equals(n.getUserId()))throw new BusinessException("技能需求不存在");needMapper.deleteById(id);}
    public List<Map<String,Object>> matches(Long currentUserId){
        List<UserSkillNeed> myNeeds=needMapper.selectList(new LambdaQueryWrapper<UserSkillNeed>().eq(UserSkillNeed::getUserId,currentUserId));if(myNeeds.isEmpty())return List.of();Set<Long> needIds=myNeeds.stream().map(UserSkillNeed::getSkillId).collect(Collectors.toSet());Set<Long> myOfferIds=offerMapper.selectList(new LambdaQueryWrapper<UserSkill>().eq(UserSkill::getUserId,currentUserId)).stream().map(UserSkill::getSkillId).collect(Collectors.toSet());
        Map<Long,Skill> skillMap=skillMapper.selectList(null).stream().collect(Collectors.toMap(Skill::getId,Function.identity()));List<User> users=userMapper.selectList(new LambdaQueryWrapper<User>().ne(User::getId,currentUserId).eq(User::getStatus,"NORMAL").eq(User::getRole,"STUDENT"));List<Map<String,Object>> result=new ArrayList<>();LocalDateTime since=LocalDateTime.now().minusDays(30);
        for(User candidate:users){Set<Long> offered=offerMapper.selectList(new LambdaQueryWrapper<UserSkill>().eq(UserSkill::getUserId,candidate.getId())).stream().map(UserSkill::getSkillId).collect(Collectors.toSet());Set<Long> intersection=new HashSet<>(needIds);intersection.retainAll(offered);if(intersection.isEmpty())continue;double skillScore=(double)intersection.size()/needIds.size();double creditScore=Math.min(candidate.getCreditScore()/100.0,1);List<Review> reviews=reviewMapper.selectList(new LambdaQueryWrapper<Review>().eq(Review::getRevieweeId,candidate.getId()));double reviewScore=reviews.isEmpty()?0.6:reviews.stream().mapToInt(Review::getRating).average().orElse(3)/5.0;long completed=orderMapper.selectCount(new LambdaQueryWrapper<TaskOrder>().eq(TaskOrder::getAccepterId,candidate.getId()).eq(TaskOrder::getStatus,"COMPLETED").ge(TaskOrder::getCompletedAt,since));double activityScore=Math.min(completed/10.0,1);double score=skillScore*.5+creditScore*.2+reviewScore*.2+activityScore*.1;Set<Long> candidateNeeds=needMapper.selectList(new LambdaQueryWrapper<UserSkillNeed>().eq(UserSkillNeed::getUserId,candidate.getId())).stream().map(UserSkillNeed::getSkillId).collect(Collectors.toSet());boolean mutual=candidateNeeds.stream().anyMatch(myOfferIds::contains);
            Map<String,Object> m=new LinkedHashMap<>();m.put("user",AuthService.userView(candidate));m.put("matchedSkills",intersection.stream().map(skillMap::get).filter(Objects::nonNull).toList());m.put("score",Math.round(score*1000)/10.0);m.put("mutualMatch",mutual);m.put("reason","覆盖 "+intersection.size()+" 项需求，信用 "+candidate.getCreditScore()+"，近30日完成 "+completed+" 单");result.add(m);}
        result.sort(Comparator.<Map<String,Object>,Boolean>comparing(m->(Boolean)m.get("mutualMatch")).reversed().thenComparing(m->-((Number)m.get("score")).doubleValue()));return result.stream().limit(10).toList();
    }
    @Transactional public SkillExchange createExchange(Long requesterId,Requests.Exchange dto){if(requesterId.equals(dto.providerId()))throw new BusinessException("不能向自己发起互助");accountService.requiredUser(dto.providerId());requiredSkill(dto.requestSkillId());if(offerMapper.selectCount(new LambdaQueryWrapper<UserSkill>().eq(UserSkill::getUserId,dto.providerId()).eq(UserSkill::getSkillId,dto.requestSkillId()))==0)throw new BusinessException("对方未提供该技能");SkillExchange e=new SkillExchange();e.setRequesterId(requesterId);e.setProviderId(dto.providerId());e.setRequestSkillId(dto.requestSkillId());e.setExchangeSkillId(dto.exchangeSkillId());e.setMessage(dto.message());e.setScheduledTime(dto.scheduledTime());e.setStatus("PENDING");e.setCreatedAt(LocalDateTime.now());exchangeMapper.insert(e);accountService.notify(dto.providerId(),"EXCHANGE_REQUEST","收到技能互助申请",accountService.requiredUser(requesterId).getNickname()+"向你发起技能互助",e.getId());return e;}
    public List<Map<String,Object>> exchanges(Long userId){return exchangeMapper.selectList(new LambdaQueryWrapper<SkillExchange>().eq(SkillExchange::getRequesterId,userId).or().eq(SkillExchange::getProviderId,userId).orderByDesc(SkillExchange::getCreatedAt)).stream().map(e->{Map<String,Object>m=new LinkedHashMap<>();m.put("exchange",e);m.put("requester",AuthService.userView(accountService.requiredUser(e.getRequesterId())));m.put("provider",AuthService.userView(accountService.requiredUser(e.getProviderId())));m.put("requestSkill",requiredSkill(e.getRequestSkillId()));if(e.getExchangeSkillId()!=null)m.put("exchangeSkill",requiredSkill(e.getExchangeSkillId()));return m;}).toList();}
    @Transactional public SkillExchange changeExchange(Long id,Long userId,String action){SkillExchange e=exchangeMapper.selectById(id);if(e==null)throw new BusinessException("互助申请不存在");String status=switch(action){case "accept"->{if(!userId.equals(e.getProviderId())||!"PENDING".equals(e.getStatus()))throw new BusinessException("当前不能接受");yield "ACCEPTED";}case "reject"->{if(!userId.equals(e.getProviderId())||!"PENDING".equals(e.getStatus()))throw new BusinessException("当前不能拒绝");yield "REJECTED";}case "start"->{if((!userId.equals(e.getProviderId())&&!userId.equals(e.getRequesterId()))||!"ACCEPTED".equals(e.getStatus()))throw new BusinessException("当前不能开始");yield "IN_PROGRESS";}case "complete"->{if((!userId.equals(e.getProviderId())&&!userId.equals(e.getRequesterId()))||!"IN_PROGRESS".equals(e.getStatus()))throw new BusinessException("当前不能完成");e.setCompletedAt(LocalDateTime.now());yield "COMPLETED";}default->throw new BusinessException("不支持的操作");};e.setStatus(status);exchangeMapper.updateById(e);return e;}
    private Skill requiredSkill(Long id){Skill s=skillMapper.selectById(id);if(s==null||!"ENABLED".equals(s.getStatus()))throw new BusinessException("技能分类不存在或已停用");return s;} private Map<String,Object> withSkill(Object record,Skill skill){Map<String,Object>m=new LinkedHashMap<>();m.put("record",record);m.put("skill",skill);return m;}
}
