package com.campuslink.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.campuslink.common.BusinessException;
import com.campuslink.domain.*;
import com.campuslink.dto.Requests;
import com.campuslink.mapper.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import java.time.LocalDateTime;
import java.util.*;

@Service @RequiredArgsConstructor
public class TaskService {
    private final TaskMapper taskMapper; private final TaskApplicationMapper applicationMapper; private final TaskOrderMapper orderMapper;
    private final TaskCompletionMapper completionMapper; private final UserMapper userMapper; private final PointCreditService pointCreditService; private final AccountService accountService;

    public Map<String,Object> list(int page,int size,String keyword,String category,String status){
        size=Math.min(Math.max(size,1),50); LambdaQueryWrapper<CampusTask> q=new LambdaQueryWrapper<>();
        if(StringUtils.hasText(keyword))q.and(w->w.like(CampusTask::getTitle,keyword).or().like(CampusTask::getDescription,keyword).or().like(CampusTask::getLocation,keyword));
        if(StringUtils.hasText(category))q.eq(CampusTask::getCategory,category); q.eq(CampusTask::getStatus,StringUtils.hasText(status)?status:"RECRUITING").orderByDesc(CampusTask::getCreatedAt);
        Page<CampusTask> result=taskMapper.selectPage(Page.of(Math.max(page,1),size),q); Map<String,Object> m=new LinkedHashMap<>();m.put("records",result.getRecords().stream().map(this::card).toList());m.put("total",result.getTotal());m.put("page",result.getCurrent());m.put("size",result.getSize());return m;
    }
    public Map<String,Object> detail(Long id){CampusTask t=requiredTask(id);Map<String,Object> m=new LinkedHashMap<>(card(t));m.put("description",t.getDescription());m.put("applicationDeadline",t.getApplicationDeadline());m.put("minCreditScore",t.getMinCreditScore());return m;}

    @Transactional public Map<String,Object> publish(Long userId,Requests.TaskCreate dto){
        User user=accountService.requiredUser(userId); if(user.getCreditScore()<60)throw new BusinessException("信用分低于60，暂不能发布任务"); LocalDateTime now=LocalDateTime.now();
        if(!dto.taskTime().isAfter(now))throw new BusinessException("任务时间必须晚于当前时间");if(!dto.applicationDeadline().isAfter(now)||!dto.applicationDeadline().isBefore(dto.taskTime()))throw new BusinessException("申请截止时间应晚于当前时间且早于任务时间");
        CampusTask t=new CampusTask();t.setPublisherId(userId);t.setTitle(dto.title());t.setCategory(dto.category());t.setDescription(dto.description());t.setLocation(dto.location());t.setTaskTime(dto.taskTime());t.setApplicationDeadline(dto.applicationDeadline());t.setRewardPoints(dto.rewardPoints());t.setMinCreditScore(dto.minCreditScore()==null?0:dto.minCreditScore());t.setStatus("RECRUITING");t.setVersion(0);t.setCreatedAt(now);t.setUpdatedAt(now);taskMapper.insert(t);
        pointCreditService.freeze(user,dto.rewardPoints(),t.getId());return detail(t.getId());
    }
    @Transactional public void apply(Long taskId,Long userId,Requests.TaskApply dto){
        CampusTask t=requiredTask(taskId);if(!"RECRUITING".equals(t.getStatus())||!t.getApplicationDeadline().isAfter(LocalDateTime.now()))throw new BusinessException("任务已停止招募");if(userId.equals(t.getPublisherId()))throw new BusinessException("不能申请自己发布的任务");User u=accountService.requiredUser(userId);if(u.getCreditScore()<t.getMinCreditScore())throw new BusinessException("信用分未达到任务要求");
        if(applicationMapper.selectCount(new LambdaQueryWrapper<TaskApplication>().eq(TaskApplication::getTaskId,taskId).eq(TaskApplication::getApplicantId,userId))>0)throw new BusinessException("你已经申请过该任务");TaskApplication a=new TaskApplication();a.setTaskId(taskId);a.setApplicantId(userId);a.setMessage(dto.message());a.setExpectedFinishTime(dto.expectedFinishTime());a.setStatus("PENDING");a.setCreatedAt(LocalDateTime.now());applicationMapper.insert(a);accountService.notify(t.getPublisherId(),"TASK_APPLICATION","收到新的任务申请",u.getNickname()+"申请了「"+t.getTitle()+"」",taskId);
    }
    public Map<String,Object> applications(Long taskId,Long publisherId,int page,int size){CampusTask t=requiredTask(taskId);if(!publisherId.equals(t.getPublisherId()))throw new BusinessException(403,"只能查看本人任务的申请");Page<TaskApplication> result=applicationMapper.selectPage(Page.of(Math.max(1,page),Math.min(100,Math.max(1,size))),new LambdaQueryWrapper<TaskApplication>().eq(TaskApplication::getTaskId,taskId).orderByDesc(TaskApplication::getCreatedAt));Map<String,Object> data=new LinkedHashMap<>();data.put("records",result.getRecords().stream().map(a->{Map<String,Object> m=new LinkedHashMap<>();m.put("application",a);m.put("applicant",AuthService.userView(accountService.requiredUser(a.getApplicantId())));return m;}).toList());data.put("total",result.getTotal());data.put("page",result.getCurrent());data.put("size",result.getSize());data.put("pages",result.getPages());return data;}
    @Transactional public Map<String,Object> acceptApplication(Long applicationId,Long publisherId){
        TaskApplication accepted=applicationMapper.selectById(applicationId);if(accepted==null||!"PENDING".equals(accepted.getStatus()))throw new BusinessException("申请已失效");CampusTask t=requiredTask(accepted.getTaskId());if(!publisherId.equals(t.getPublisherId()))throw new BusinessException(403,"无权选择该任务接取者");if(!"RECRUITING".equals(t.getStatus()))throw new BusinessException("任务状态已变化");
        LocalDateTime now=LocalDateTime.now();int claimed=taskMapper.update(null,new LambdaUpdateWrapper<CampusTask>().eq(CampusTask::getId,t.getId()).eq(CampusTask::getStatus,"RECRUITING").set(CampusTask::getStatus,"WAIT_EXECUTE").set(CampusTask::getUpdatedAt,now).setSql("version = version + 1"));if(claimed!=1)throw new BusinessException("任务已被其他申请抢先确认，请刷新后重试");
        applicationMapper.update(null,new LambdaUpdateWrapper<TaskApplication>().eq(TaskApplication::getTaskId,t.getId()).eq(TaskApplication::getStatus,"PENDING").set(TaskApplication::getStatus,"REJECTED"));accepted.setStatus("ACCEPTED");applicationMapper.updateById(accepted);
        TaskOrder order=new TaskOrder();order.setTaskId(t.getId());order.setPublisherId(publisherId);order.setAccepterId(accepted.getApplicantId());order.setStatus("WAIT_EXECUTE");order.setVersion(0);order.setAcceptedAt(now);order.setUpdatedAt(now);orderMapper.insert(order);accountService.notify(order.getAccepterId(),"ORDER_STATUS","任务申请已通过","你已成为「"+t.getTitle()+"」的接取者",order.getId());return orderView(order);
    }
    public Map<String,Object> mine(Long userId){Map<String,Object> m=new LinkedHashMap<>();m.put("published",taskMapper.selectList(new LambdaQueryWrapper<CampusTask>().eq(CampusTask::getPublisherId,userId).orderByDesc(CampusTask::getCreatedAt)).stream().map(t->{Map<String,Object> item=new LinkedHashMap<>(card(t));TaskOrder order=orderMapper.selectOne(new LambdaQueryWrapper<TaskOrder>().eq(TaskOrder::getTaskId,t.getId()));if(order!=null){item.put("orderId",order.getId());item.put("orderStatus",order.getStatus());}return item;}).toList());m.put("accepted",orderMapper.selectList(new LambdaQueryWrapper<TaskOrder>().eq(TaskOrder::getAccepterId,userId).orderByDesc(TaskOrder::getAcceptedAt)).stream().map(this::orderView).toList());return m;}
    @Transactional public void cancel(Long taskId,Long userId){CampusTask t=requiredTask(taskId);if(!userId.equals(t.getPublisherId()))throw new BusinessException(403,"只能取消本人发布的任务");if(!"RECRUITING".equals(t.getStatus()))throw new BusinessException("当前阶段不能直接取消，请发起异常处理");User u=accountService.requiredUser(userId);pointCreditService.refund(u,t.getRewardPoints(),t.getId());t.setStatus("CANCELLED");t.setUpdatedAt(LocalDateTime.now());taskMapper.updateById(t);}

    @Transactional public Map<String,Object> startOrder(Long orderId,Long userId){TaskOrder o=requiredOrder(orderId);if(!userId.equals(o.getAccepterId()))throw new BusinessException(403,"只有接取者可以开始任务");if("IN_PROGRESS".equals(o.getStatus()))return orderView(o);if(!"WAIT_EXECUTE".equals(o.getStatus()))throw new BusinessException("当前状态不能开始任务");LocalDateTime now=LocalDateTime.now();o.setStatus("IN_PROGRESS");o.setStartedAt(now);o.setUpdatedAt(now);orderMapper.updateById(o);syncTask(o,"IN_PROGRESS");accountService.notify(o.getPublisherId(),"ORDER_STATUS","任务已开始","接取者已开始执行任务",o.getId());return orderView(o);}
    @Transactional public Map<String,Object> submitCompletion(Long orderId,Long userId,Requests.Completion dto){TaskOrder o=requiredOrder(orderId);if(!userId.equals(o.getAccepterId()))throw new BusinessException(403,"只有接取者可以提交结果");if(!"IN_PROGRESS".equals(o.getStatus()))throw new BusinessException("任务不在进行中");TaskCompletion c=new TaskCompletion();c.setOrderId(orderId);c.setDescription(dto.description());c.setProofUrl(dto.proofUrl());c.setSubmitTime(LocalDateTime.now());c.setReviewStatus("PENDING");completionMapper.insert(c);o.setStatus("WAIT_ACCEPTANCE");o.setUpdatedAt(LocalDateTime.now());orderMapper.updateById(o);syncTask(o,"WAIT_ACCEPTANCE");accountService.notify(o.getPublisherId(),"ORDER_STATUS","任务待验收","接取者已提交完成结果",o.getId());return orderView(o);}
    @Transactional public Map<String,Object> approve(Long orderId,Long userId){TaskOrder o=requiredOrder(orderId);if(!userId.equals(o.getPublisherId()))throw new BusinessException(403,"只有发布者可以验收");if(!"WAIT_ACCEPTANCE".equals(o.getStatus()))throw new BusinessException("任务当前不待验收");TaskCompletion c=latestPending(o.getId());c.setReviewStatus("APPROVED");completionMapper.updateById(c);CampusTask t=requiredTask(o.getTaskId());pointCreditService.settle(accountService.requiredUser(o.getPublisherId()),accountService.requiredUser(o.getAccepterId()),t.getRewardPoints(),o.getId());LocalDateTime now=LocalDateTime.now();o.setStatus("COMPLETED");o.setCompletedAt(now);o.setUpdatedAt(now);orderMapper.updateById(o);syncTask(o,"COMPLETED");accountService.notify(o.getAccepterId(),"ORDER_STATUS","任务验收通过","任务积分已到账",o.getId());return orderView(o);}
    @Transactional public Map<String,Object> reject(Long orderId,Long userId,Requests.Reject dto){TaskOrder o=requiredOrder(orderId);if(!userId.equals(o.getPublisherId()))throw new BusinessException(403,"只有发布者可以驳回");if(!"WAIT_ACCEPTANCE".equals(o.getStatus()))throw new BusinessException("任务当前不待验收");TaskCompletion c=latestPending(o.getId());c.setReviewStatus("REJECTED");c.setRejectReason(dto.reason());completionMapper.updateById(c);o.setStatus("IN_PROGRESS");o.setUpdatedAt(LocalDateTime.now());orderMapper.updateById(o);syncTask(o,"IN_PROGRESS");accountService.notify(o.getAccepterId(),"ORDER_STATUS","任务验收被驳回",dto.reason(),o.getId());return orderView(o);}
    public Map<String,Object> order(Long orderId,Long userId){TaskOrder o=requiredOrder(orderId);if(!userId.equals(o.getPublisherId())&&!userId.equals(o.getAccepterId()))throw new BusinessException(403,"无权查看该订单");return orderView(o);}

    private Map<String,Object> card(CampusTask t){User p=userMapper.selectById(t.getPublisherId());Map<String,Object> m=new LinkedHashMap<>();m.put("id",t.getId());m.put("publisherId",t.getPublisherId());m.put("title",t.getTitle());m.put("category",t.getCategory());m.put("location",t.getLocation());m.put("taskTime",t.getTaskTime());m.put("rewardPoints",t.getRewardPoints());m.put("status",t.getStatus());m.put("createdAt",t.getCreatedAt());if(p!=null){m.put("publisherNickname",p.getNickname());m.put("publisherCredit",p.getCreditScore());}return m;}
    private Map<String,Object> orderView(TaskOrder o){Map<String,Object> m=new LinkedHashMap<>();m.put("order",o);m.put("task",detail(o.getTaskId()));m.put("publisher",AuthService.userView(accountService.requiredUser(o.getPublisherId())));m.put("accepter",AuthService.userView(accountService.requiredUser(o.getAccepterId())));m.put("completions",completionMapper.selectList(new LambdaQueryWrapper<TaskCompletion>().eq(TaskCompletion::getOrderId,o.getId()).orderByDesc(TaskCompletion::getSubmitTime)));return m;}
    private CampusTask requiredTask(Long id){CampusTask t=taskMapper.selectById(id);if(t==null)throw new BusinessException(404,"任务不存在");return t;} private TaskOrder requiredOrder(Long id){TaskOrder o=orderMapper.selectById(id);if(o==null)throw new BusinessException(404,"订单不存在");return o;} private TaskCompletion latestPending(Long oid){TaskCompletion c=completionMapper.selectOne(new LambdaQueryWrapper<TaskCompletion>().eq(TaskCompletion::getOrderId,oid).eq(TaskCompletion::getReviewStatus,"PENDING").orderByDesc(TaskCompletion::getSubmitTime).last("limit 1"));if(c==null)throw new BusinessException("没有待验收的提交");return c;} private void syncTask(TaskOrder o,String status){CampusTask t=requiredTask(o.getTaskId());t.setStatus(status);t.setUpdatedAt(LocalDateTime.now());taskMapper.updateById(t);}
}
